module cow {

	struct Reading {
		string name;
		float voltage;
		float current;
		float watts;
		float vars;
		float frequency;
		long timestamp;
		boolean isOpen;
		float stateOfCharge;
	};
	#pragma keylist Reading name

	struct OpenClose {
		string name;
		boolean isOpen;
	};
	#pragma keylist OpenClose name

	struct SetWatts {
		string name;
		float watts;
	};
	#pragma keylist SetWatts name

	struct SvSc {
		string name;
		boolean isSv;
	};
	#pragma keylist SvSc name

};



